sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2

git:
  depth: 9999999

language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - tools # https://github.com/travis-ci/travis-ci/issues/6059
    - platform-tools
    - android-16
    - android-28
    - build-tools-28.0.3

before_script:
  - export TERM=dumb

script:
  - set -e
  - cd $TRAVIS_BUILD_DIR/AndroidAnnotations
  - ./mvnw install -P travis --quiet
  - cd $TRAVIS_BUILD_DIR/examples/maven
  - ./mvnw install
  - cd $TRAVIS_BUILD_DIR/examples/gradle
  - ./gradlew assembleDebug
  - cd $TRAVIS_BUILD_DIR/examples/kotlin
  - ./gradlew assembleDebug
  - cd $TRAVIS_BUILD_DIR/examples/RoboGuiceExample
  - ./gradlew assembleDebug
  - cd $TRAVIS_BUILD_DIR
  - ./check_missing_copyright.sh
  - set +e

after_success:
  - if [[ $TRAVIS_REPO_SLUG == 'androidannotations/androidannotations' && $TRAVIS_BRANCH == 'develop' && $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_JDK_VERSION == 'oraclejdk8' ]]; then cd $TRAVIS_BUILD_DIR/AndroidAnnotations && ./mvnw -DskipTests -Dquiet -s ../settings.xml deploy ; fi

notifications:
  webhooks:
    urls:
      secure: BOoKIc3qLKIx4efsNqg3Z6ErgBIF6xKKljozg5/GxaSPr9R58W/rOfyNJKtVpzfGlD0Z0e8psTb5FPGs/CNRprUJwCANGJ72FIc+NuEdO0+kLpvsvkl0yWJc5WHuOzqTTlsuPjfATB820AFTboIoV9tQ9wNhHB4vpyRqKPErdjg=
    on_success: change
    on_failure: always
    on_start: false
  email: false
